# Generated by Django 4.1.3 on 2022-12-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttags',
            name='tag_name',
            field=models.CharField(max_length=250, verbose_name='name of the tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250, verbose_name='title of the post'),
        ),
    ]
